---
/**:
  robotnik_base_control:
    ros__parameters:
      publish_rate: 50

      #General Params
      profile: base
      debug: true
      open_loop: true

      #Timeouts
      joint_command_timeout: 0.1
      cmd_vel_timeout: 2.0

      #Odom
      odom_frame_id: $(var frame_prefix)odom
      base_frame_id: $(var frame_prefix)base_footprint
      use_2D_odom: true

      #Kinematics Params
      wheel_radius: 0.1745
      wheel_base:   1.34
      track_width:  1.23
      min_turning_ratio:  1.0

      # Topics
      cmd_vel_topic: ~/cmd_vel_unstamped
      odom_topic: ~/odom
      imu_topic: imu/data
      emergency_topic: robotnik_base_hw/emergency_stop
      joint_control_topic: ~/joint_control_command

      # RBVogui XL Controller Params
      max_steering_position_error: 0.3

      #Cartesian and wheels limits
      base:
        linear:
          x:
            velocity:
              min: -0.8
              max:  0.8
            acceleration:
              min: -1.0
              max:  1.0
          y:
            velocity:
              min: -0.8
              max:  0.8
            acceleration:
              min: -1.0
              max:  1.0
        angular:
          z:
            velocity:
              min: -0.8
              max:  0.8
            acceleration:
              min: -1.2
              max:  1.2

        front_right:
          traction:
            joint_name: $(var frame_prefix)front_right_wheel_joint
            limits:
              velocity:
                min: -6.0
                max:  6.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: $(var frame_prefix)front_right_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        front_left:
          traction:
            joint_name: $(var frame_prefix)front_left_wheel_joint
            limits:
              velocity:
                min: -6.0
                max:  6.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: $(var frame_prefix)front_left_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        back_right:
          traction:
            joint_name: $(var frame_prefix)back_right_wheel_joint
            limits:
              velocity:
                min: -6.0
                max:  6.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: $(var frame_prefix)back_right_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        back_left:
          traction:
            joint_name: $(var frame_prefix)back_left_wheel_joint
            limits:
              velocity:
                min: -6.0
                max:  6.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: $(var frame_prefix)back_left_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8
