waypoints:
  waypoint0:
    pose:
      - -2.9943239688873291
      - 1.3437891006469727
      - 0
    orientation:
      - 0.83821804295800306
      - 0
      - 0
      - 0.54533522943200308
  waypoint1:
    pose:
      - -1.7758164405822754
      - 1.6370080709457397
      - 0
    orientation:
      - 0.88453038646449977
      - 0
      - 0
      - 0.46648257783218722
  waypoint2:
    pose:
      - -0.52718907594680786
      - 1.888986349105835
      - 0
    orientation:
      - 0.87941497803924895
      - 0
      - 0
      - 0.47605598032188123
  waypoint3:
    pose:
      - 0.7069936990737915
      - 2.1444528102874756
      - 0
    orientation:
      - 0.87500989976915511
      - 0
      - 0
      - 0.48410502507820885