/**:
  planner_server:
    ros__parameters:
      expected_planner_frequency: 0.2
      planner_plugins: ["GridBased"]
      costmap_update_timeout: 1.0
      GridBased:
        plugin: "nav2_navfn_planner::NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: true

  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        global_frame: robot_map
        robot_base_frame: robot_base_link
        footprint: "[[0.4,-0.35],[0.4,0.35],[-0.4,0.35],[-0.4,-0.35]]"
        footprint_padding: 0.05
        # robot_radius: 0.6 #0.60
        resolution: 0.05 # resolution: 0.025
        track_unknown_space: true
        plugins: ["static_layer", "inflation_layer"]
        static_layer:
          map_topic: /robot/map
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: true
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 4.00
          inflation_radius: 1.5
        always_send_full_costmap: true

